### ISSUE TITLE
Unable to install package on concrete5 8.5.1

### ISSUE THREAD

**Issue by alessandrocrovato** [concrete5/brandcentral#1]
I get this error trying to install the package on a clean 8.5.1 installation (xammp): Unable to install brand_central. Please check that this package has been updated for 5.7.

**Comment by KorvinSzanto** [comment]
Whoops! Looks like we named the composer package incorrectly. I've resolved this by changing the composer package name to `concrete5/brand_central`. You can fix this by replacing the requirement in your composer.json with that.
